//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGPCE.Sigemad.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGPCE.Sigemad.Application.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto no puede superar 500 caracteres.
        /// </summary>
        public static string AsuntoMaxLegth {
            get {
                return ResourceManager.GetString("AsuntoMaxLegth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto es obligatorio.
        /// </summary>
        public static string AsuntoNoNulo {
            get {
                return ResourceManager.GetString("AsuntoNoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asunto no puede ser vacio.
        /// </summary>
        public static string AsuntoNoVacio {
            get {
                return ResourceManager.GetString("AsuntoNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad que dirige no puede estar en blanco.
        /// </summary>
        public static string AutoridadQueDirigeEnBlanco {
            get {
                return ResourceManager.GetString("AutoridadQueDirigeEnBlanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad Que Dirige es obligatorio.
        /// </summary>
        public static string AutoridadQueDirigeObligatorio {
            get {
                return ResourceManager.GetString("AutoridadQueDirigeObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase de Suceso es obligatorio.
        /// </summary>
        public static string ClaseSucesoObligatorio {
            get {
                return ResourceManager.GetString("ClaseSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominacion no puede exceder los 255 caracteres.
        /// </summary>
        public static string DenominacionMaxLength {
            get {
                return ResourceManager.GetString("DenominacionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        public static string DenominacionNoVacio {
            get {
                return ResourceManager.GetString("DenominacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denominacion es obligatorio.
        /// </summary>
        public static string DenominacionObligatorio {
            get {
                return ResourceManager.GetString("DenominacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad Menor es obligatorio.
        /// </summary>
        public static string EntidadMenorObligatorio {
            get {
                return ResourceManager.GetString("EntidadMenorObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Suceso es obligatorio.
        /// </summary>
        public static string EstadoSucesoObligatorio {
            get {
                return ResourceManager.GetString("EstadoSucesoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolucion es obligatorio.
        /// </summary>
        public static string EvolucionObligatorio {
            get {
                return ResourceManager.GetString("EvolucionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FechaHora no puede ser vacio.
        /// </summary>
        public static string FechaHoraNoVacio {
            get {
                return ResourceManager.GetString("FechaHoraNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha hora es obligatoria.
        /// </summary>
        public static string FechaHoraObligatorio {
            get {
                return ResourceManager.GetString("FechaHoraObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio es obligatoria.
        /// </summary>
        public static string FechaInicioObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicio PMA es obligatoria.
        /// </summary>
        public static string FechaInicioPMAObligatorio {
            get {
                return ResourceManager.GetString("FechaInicioPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría CECOPI no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionCECOPInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionCECOPInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion CECOPI es obligatoria.
        /// </summary>
        public static string GeoPosicionCECOPIObligatoria {
            get {
                return ResourceManager.GetString("GeoPosicionCECOPIObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion es obligatorio.
        /// </summary>
        public static string GeoPosicionObligatorio {
            get {
                return ResourceManager.GetString("GeoPosicionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La geometría PMA no es válida, sistema de referencia no es Wgs84.
        /// </summary>
        public static string GeoPosicionPMAInvalida {
            get {
                return ResourceManager.GetString("GeoPosicionPMAInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GeoPosicion PMA es obligatorio.
        /// </summary>
        public static string GeoPosicionPMAObligatoria {
            get {
                return ResourceManager.GetString("GeoPosicionPMAObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id no puede ser vacio.
        /// </summary>
        public static string IdNoVacio {
            get {
                return ResourceManager.GetString("IdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id es obligatorio.
        /// </summary>
        public static string IdObligatorio {
            get {
                return ResourceManager.GetString("IdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso asociado no puede ser vacio.
        /// </summary>
        public static string IdSucesoAsociadoNoVacio {
            get {
                return ResourceManager.GetString("IdSucesoAsociadoNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id suceso asociado es oblogatorio.
        /// </summary>
        public static string IdSucesoAsociadoObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoAsociadoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso principal no puede ser vacio.
        /// </summary>
        public static string IdSucesoPrincipalNoVacio {
            get {
                return ResourceManager.GetString("IdSucesoPrincipalNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Suceso principal es obligatorio.
        /// </summary>
        public static string IdSucesoPrincipalObligatorio {
            get {
                return ResourceManager.GetString("IdSucesoPrincipalObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Incendio no puede estar vacio.
        /// </summary>
        public static string IncendioIdNoVacio {
            get {
                return ResourceManager.GetString("IncendioIdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Incendio es obligatorio.
        /// </summary>
        public static string IncendioIdObligatorio {
            get {
                return ResourceManager.GetString("IncendioIdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incendio es inválido.
        /// </summary>
        public static string IncendioInvalido {
            get {
                return ResourceManager.GetString("IncendioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incendio es obligatorio.
        /// </summary>
        public static string IncendioObligatorio {
            get {
                return ResourceManager.GetString("IncendioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedioId no puede ser vacio.
        /// </summary>
        public static string MedioIdNoVacio {
            get {
                return ResourceManager.GetString("MedioIdNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MedioId es obligatorio.
        /// </summary>
        public static string MedioIdObligatorio {
            get {
                return ResourceManager.GetString("MedioIdObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio CECOPI es invalido.
        /// </summary>
        public static string MunicipioCECOPIInvalido {
            get {
                return ResourceManager.GetString("MunicipioCECOPIInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio CECOPI es Obligatorio.
        /// </summary>
        public static string MunicipioCECOPIObligatorio {
            get {
                return ResourceManager.GetString("MunicipioCECOPIObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio es inválido.
        /// </summary>
        public static string MunicipioInvalido {
            get {
                return ResourceManager.GetString("MunicipioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio es obligatorio.
        /// </summary>
        public static string MunicipioObligatorio {
            get {
                return ResourceManager.GetString("MunicipioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio CECOPI es invalido.
        /// </summary>
        public static string MunicipioPMAiInvalido {
            get {
                return ResourceManager.GetString("MunicipioPMAiInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio PMA es Obligatorio.
        /// </summary>
        public static string MunicipioPMAObligatorio {
            get {
                return ResourceManager.GetString("MunicipioPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais es inválido.
        /// </summary>
        public static string PaisInvalido {
            get {
                return ResourceManager.GetString("PaisInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais es obligatorio.
        /// </summary>
        public static string PaisObligatorio {
            get {
                return ResourceManager.GetString("PaisObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia CECOPI es invalido.
        /// </summary>
        public static string ProvinciaCECOPIInvalido {
            get {
                return ResourceManager.GetString("ProvinciaCECOPIInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia CECOPI es obligatorio.
        /// </summary>
        public static string ProvinciaCECOPIObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaCECOPIObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia es inválido.
        /// </summary>
        public static string ProvinciaInvalido {
            get {
                return ResourceManager.GetString("ProvinciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia es obligatoria.
        /// </summary>
        public static string ProvinciaObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia PMA es invalido.
        /// </summary>
        public static string ProvinciaPMAInvalido {
            get {
                return ResourceManager.GetString("ProvinciaPMAInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia PMA es obligatorio.
        /// </summary>
        public static string ProvinciaPMAObligatorio {
            get {
                return ResourceManager.GetString("ProvinciaPMAObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        public static string TerritorioInvalido {
            get {
                return ResourceManager.GetString("TerritorioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neutral.
        /// </summary>
        public static string TerritorioObligatorio {
            get {
                return ResourceManager.GetString("TerritorioObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo dirección emergencia es invalido.
        /// </summary>
        public static string TipoDireccionEmergenciaInvalido {
            get {
                return ResourceManager.GetString("TipoDireccionEmergenciaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo dirección emergencia es obligatorio.
        /// </summary>
        public static string TipoDireccionEmergenciaObligatorio {
            get {
                return ResourceManager.GetString("TipoDireccionEmergenciaObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación no puede ser vacio.
        /// </summary>
        public static string UbicacionNoVacio {
            get {
                return ResourceManager.GetString("UbicacionNoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación es obligatorio.
        /// </summary>
        public static string UbicacionObligatorio {
            get {
                return ResourceManager.GetString("UbicacionObligatorio", resourceCulture);
            }
        }
    }
}
