SET IDENTITY_INSERT dbo.ProcedenciaDestino ON;

INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1,N'112 Andalucía'),
	 (2,N'112 Asturias'),
	 (3,N'112 Galicia'),
	 (11,N'UME'),
	 (12,N'Embajada'),
	 (13,N'DIGENPOL'),
	 (14,N'112 Canarias'),
	 (61,N'Subdelegación del Gobierno en Granada'),
	 (63,N'DISSC'),
	 (68,N'Subdelegación del Gobierno en Zamora');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (70,N'Subdelegación del Gobierno en Huelva'),
	 (71,N'Subdelegación del Gobierno en Cuenca'),
	 (72,N'Subdelegación del Gobierno en Segovia'),
	 (75,N'Subdelegación del Gobierno en Guadalajara'),
	 (76,N'Subdelegación del Gobierno en Albacete'),
	 (77,N'Subdelegación del Gobierno en Santa Cruz de Tenerife'),
	 (79,N'Delegación del Gobierno en Illes Balears'),
	 (80,N'Subdelegación del Gobierno en Tarragona'),
	 (82,N'Subdelegación del Gobierno en Cáceres'),
	 (83,N'Subdelegación del Gobierno en Almería');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (90,N'Subdelegación del Gobierno en Jaén'),
	 (92,N'Subdelegación del Gobierno en Córdoba'),
	 (93,N'Subdelegación del Gobierno en Salamanca'),
	 (95,N'Subdelegación del Gobierno en Soria'),
	 (97,N'Subdelegación del Gobierno en Ourense'),
	 (100,N'Subdelegación del Gobierno en Lleida'),
	 (105,N'Subdelegación del Gobierno en Huesca'),
	 (107,N'Subdelegación del Gobierno en Pontevedra'),
	 (108,N'Subdelegación del Gobierno en A Coruña'),
	 (111,N'Subdelegación del Gobierno en Lugo');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (114,N'Delegación del Gobierno en Canarias'),
	 (115,N'Consulado de España en Casablanca'),
	 (116,N'Varios'),
	 (117,N'Centro Control Aéreo de Canarias'),
	 (119,N'Centro Control Aéreo de Sevilla'),
	 (120,N'Centro de Control Aéreo de Madrid'),
	 (121,N'Embajada de España en Marruecos'),
	 (122,N'Cuartel General del Ejército de Tierra'),
	 (126,N'CECAT'),
	 (130,N'RENFE');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (131,N'Dirección General de Tráfico'),
	 (132,N'Subdelegación del Gobierno en Teruel'),
	 (135,N'Embajada de España en Argelia'),
	 (142,N'Centro de Control Aéreo de Barcelona'),
	 (143,N'Aeropuerto de Zaragoza'),
	 (144,N'AENA'),
	 (145,N'Centro de Control Aéreo de Palma de Mallorca'),
	 (149,N'Escuela Nacional de Protección Civil'),
	 (150,N'Red Eléctrica de España'),
	 (151,N'ERCC - Comisión Europea');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (156,N'Comisión Europea'),
	 (160,N'112 Extremadura'),
	 (161,N'Cruz Roja Española'),
	 (162,N'CLH'),
	 (163,N'Subdelegación del Gobierno en Palencia'),
	 (167,N'112 Madrid'),
	 (173,N'IBERDROLA'),
	 (174,N'112 Castilla y León'),
	 (176,N'Bomberos de Barcelona'),
	 (177,N'Bomberos de Girona');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (181,N'DGPCE'),
	 (185,N'Ministerio de Defensa'),
	 (199,N'Europa press'),
	 (204,N'Embajada de Francia en España'),
	 (207,N'JEMACON'),
	 (209,N'CECOMDEF'),
	 (214,N'Dirección Insular de la AGE en Ibiza y Formentera'),
	 (215,N'ADCIF'),
	 (216,N'Subdelegación del Gobierno en Toledo'),
	 (220,N'Ministerio del Interior');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (224,N'11'),
	 (225,N'Subdelegación del Gobierno en Guipúzcoa'),
	 (242,N'112 Illes Balears'),
	 (243,N'SAAR, S.L. Servicios anfibios aéreos rescate'),
	 (244,N'Bomberos del Ayuntamiento de Madrid'),
	 (245,N'GISPE'),
	 (246,N'Particular'),
	 (247,N'Estado Mayor del Aire de Marruecos'),
	 (250,N'Ministerio de Asuntos Exteriores y de Cooperación'),
	 (253,N'Bomberos de Cádiz');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (255,N'Embajada de España en la República Checa'),
	 (257,N'Subsecretario de Presidencia'),
	 (258,N'Diputación Provincial de Zaragoza'),
	 (260,N'PROCOPTERE'),
	 (262,N'112 Aragón'),
	 (263,N'C.A. La Rioja'),
	 (266,N'C.A. Aragón'),
	 (267,N'C.A. País Vasco'),
	 (274,N'112 Cantabria'),
	 (276,N'Dirección General de Aviación Civil');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (277,N'Ayuntamiento de Madrid'),
	 (279,N'112 Comunidad Valenciana'),
	 (284,N'Bomberos de Asturias'),
	 (286,N'TRAGSA'),
	 (290,N'REMER'),
	 (293,N'Secretaría de Estado de Seguridad'),
	 (294,N'CEPIC'),
	 (306,N'Embajada de Albania en Marruecos'),
	 (309,N'Subdelegación del Gobierno en Las Palmas'),
	 (311,N'Delegación del Gobierno en Andalucía');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (312,N'COS Guardia Civil Córdoba'),
	 (315,N'Chapman freeborn'),
	 (325,N'JECOM'),
	 (334,N'AEMET'),
	 (337,N'COS Guardia Civil Teruel'),
	 (349,N'CECOPI'),
	 (352,N'Delegación Provincial de la Junta en Cuenca'),
	 (353,N'DGMNyPF'),
	 (355,N'COS Guardia Civil Cáceres'),
	 (367,N'Subdelegación del Gobierno en León');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (375,N'Subdelegación del Gobierno en Illes Balears'),
	 (376,N'DSS REMFIRESAT'),
	 (377,N'CSN'),
	 (378,N'Subdelegación del Gobierno en Sevilla'),
	 (384,N'Prensa digital'),
	 (385,N'Subdelegación del Gobierno en Vizcaya'),
	 (388,N'Subdelegación del Gobierno en Cadiz'),
	 (390,N'EADRCC (OTAN)'),
	 (398,N'Delegación del Gobierno en Castilla-La Mancha'),
	 (399,N'Subdelegación del Gobierno en Zaragoza');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (403,N'Delegación del Gobierno en Comunidad Valenciana '),
	 (405,N'Cuartel General del Ejército del Aire'),
	 (407,N'Subdelegación del Gobierno en Málaga'),
	 (430,N'MARM'),
	 (442,N'Delegación del Gobierno en Castilla y León'),
	 (443,N'Delegación del Gobierno en Cantabria'),
	 (444,N'Subdelegación del Gobierno en Burgos'),
	 (445,N'Delegación del Gobierno en Melilla'),
	 (446,N'Subdelegación del Gobierno en Avila'),
	 (447,N'Delegación del Gobierno en Madrid');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (448,N'112'),
	 (449,N'Subdelegación del Gobierno en Castellón'),
	 (450,N'Subdelegación del Gobierno en Girona'),
	 (451,N'Subdelegación del Gobierno en Alicante'),
	 (452,N'Subdelegación del Gobierno en Ciudad Real'),
	 (453,N'Sin especificar'),
	 (454,N'Delegación del Gobierno en Galicia'),
	 (455,N'Delegación del Gobierno en La Rioja'),
	 (456,N'Delegación del Gobierno en Asturias'),
	 (457,N'Delegación del Gobierno en País Vasco');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (460,N'Delegación del Gobierno en Cataluña'),
	 (461,N'Delegación del Gobierno en Murcia'),
	 (462,N'Delegación del Gobierno en Extremadura'),
	 (465,N'Delegación del Gobierno en Aragón'),
	 (466,N'Dirección General de Carreteras'),
	 (470,N'Delegación del Gobierno en Navarra'),
	 (471,N'Subdelegación del Gobierno en Barcelona'),
	 (473,N'Delegación del Gobierno en Ceuta'),
	 (474,N'Empresa AURECA'),
	 (475,N'Confederación Hidrográfica del Tajo');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (476,N'Empresa GRUPISA'),
	 (477,N'Auto Res'),
	 (479,N'Policía Municipal de Melilla'),
	 (480,N'Euskotren'),
	 (482,N'Telefónica'),
	 (483,N'Medios de Comunicación'),
	 (486,N'Ayuntamiento de Santa Elena'),
	 (487,N'Confederación Hidrográfica del Ebro'),
	 (488,N'Ayuntamiento de Tudela'),
	 (489,N'Policía Municipal de Tudela');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (491,N'Subdelegación del Gobierno en Alava'),
	 (495,N'Policía Municipal de Calatayud'),
	 (497,N'Confederación Hidrográfica del Duero'),
	 (499,N'Centro de Gestión de Tráfico de Madrid'),
	 (501,N'ENDESA'),
	 (502,N'Aeropuerto de Sevilla'),
	 (503,N'Base aérea de Getafe'),
	 (506,N'Base aérea de Cuatro Vientos'),
	 (515,N'1913'),
	 (516,N'Carta Internacional Espacio y Grandes Catástrofes');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (519,N'Consulado de EEUU en Barcelona'),
	 (521,N'IGN'),
	 (525,N'Ayuntamiento de Parcent'),
	 (526,N'Ayuntamiento de Xaló'),
	 (528,N'112 Melilla'),
	 (531,N'Cabildo Insular de la Isla del Hierro'),
	 (536,N'SASEMAR'),
	 (538,N'Ayuntamiento de Coslada'),
	 (541,N'Ayuntamiento de El Carpio de Tajo (Toledo)'),
	 (543,N'GIGE');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (557,N'Dirección General de Carreteras de la CAM'),
	 (560,N'ADIF'),
	 (562,N'GPV Madrid'),
	 (584,N'COS Guardia Civil Málaga'),
	 (585,N'COS Guardia Civil Almería'),
	 (586,N'112 Cataluña'),
	 (588,N'COS Guardia Civil Badajoz'),
	 (591,N'COS Guardia Civil Ciudad Real'),
	 (594,N'112 Navarra'),
	 (595,N'Dirección General de la Policía y de la Guardia Civil');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (597,N'COS Guardia Civil Alicante'),
	 (603,N'COS Guardia Civil'),
	 (612,N'CECEM'),
	 (618,N'COS Guardia Civil Zaragoza'),
	 (852,N'112 La Rioja'),
	 (853,N'Satélite'),
	 (856,N'7466'),
	 (866,N'IAEA'),
	 (872,N'CNCS'),
	 (875,N'Autoridad Portuaria de Algeciras');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (876,N'Estrella Seguros'),
	 (877,N'CECOP Algeciras'),
	 (878,N'IBERIA'),
	 (882,N'Areas de descanso DGT'),
	 (883,N'Barcelona'),
	 (885,N'Embajada de Paraguay en España'),
	 (886,N'Instituto Nacional de Toxicología'),
	 (887,N'Hospital De Monde (Francia)'),
	 (889,N'Seguros Estrella'),
	 (890,N'Hermes S.L.');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (892,N'HERMES,S.L'),
	 (896,N'Desconocida'),
	 (901,N'Autoridad Portuaria de Almería'),
	 (902,N'Oficina de Coordinación de la AGE en Campo de Gibraltar'),
	 (905,N'ce'),
	 (907,N'Protección Civil de Majadahonda'),
	 (910,N'Instituto Nacional de Meteorología'),
	 (911,N'Industrias La Tuna'),
	 (913,N'BP'),
	 (915,N'GPV Zaragoza');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (916,N'DIA WASHINGTON DC'),
	 (920,N'Dow Chemical (Tarragona)'),
	 (921,N'Natra Cacao'),
	 (922,N'UNECE'),
	 (923,N'ENUSA'),
	 (925,N'ETSA'),
	 (926,N'Centro ICE del Reino Unido (NCEC)'),
	 (927,N'Centro ICE de Alemania (BASF)'),
	 (932,N'ANPC-Portugal'),
	 (933,N'ERCROS Monzón');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (935,N'Fax'),
	 (943,N'SAFEMA'),
	 (947,N'Instituto de Salud Carlos III'),
	 (951,N'Embajada de Guatemala en España'),
	 (952,N'Ministerio de Fomento'),
	 (958,N'AEM'),
	 (965,N'IBERPISTAS'),
	 (967,N'Agencia EFE'),
	 (973,N'112 Murcia'),
	 (1009,N'2657');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1011,N'112 País Vasco'),
	 (1013,N'FEVE'),
	 (1018,N'112 Castilla-La Mancha'),
	 (1019,N'112 Santa Cruz de Tenerife'),
	 (1020,N'AECID'),
	 (1021,N'Aeropuerto de Madrid'),
	 (1022,N'Aeropuerto de Noain (Navarra)'),
	 (1023,N'Aeropuerto de Pamplona'),
	 (1024,N'Alemania, Protección civil'),
	 (1025,N'Andorra, Protección Civil');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1026,N'Austria, Protección Civil'),
	 (1027,N'Base aérea de Marsella'),
	 (1028,N'Bélgica, Protección Civil'),
	 (1029,N'Bomberos de Cataluña'),
	 (1030,N'Bomberos de Ceuta'),
	 (1031,N'Bomberos de Murcia'),
	 (1032,N'Bulgaria, Protección Civil'),
	 (1033,N'C.A. Andalucía'),
	 (1034,N'C.A. Aragón - Protección Civil'),
	 (1035,N'C.A. Canarias');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1036,N'C.A. Cantabria'),
	 (1037,N'C.A. Castilla y León'),
	 (1038,N'C.A. Castilla-La Mancha'),
	 (1039,N'C.A. Cataluña'),
	 (1040,N'C.A. Cataluña - Protección Civil'),
	 (1041,N'C.A. Comunidad Valenciana'),
	 (1042,N'C.A. Comunidad Valenciana - Protección Civil'),
	 (1043,N'C.A. Extremadura'),
	 (1044,N'C.A. Galicia'),
	 (1045,N'C.A. Galicia - Protección Civil');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1046,N'C.A. Illes Balears'),
	 (1047,N'C.A. Murcia'),
	 (1048,N'C.A. Navarra'),
	 (1049,N'C.A. País Vasco - Protección Civil'),
	 (1050,N'CECOP'),
	 (1051,N'Centro de Gestión de Tráfico de Zaragoza'),
	 (1052,N'Centro ICE de Italia (SET)'),
	 (1053,N'Confederación Hidrográfica del Cantábrico'),
	 (1054,N'Consulado de Portugal en Salamanca'),
	 (1055,N'COS Guardia Civil Albacete');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1056,N'COS Guardia Civil Algeciras'),
	 (1057,N'COS Guardia Civil Asturias'),
	 (1058,N'COS Guardia Civil Ávila'),
	 (1059,N'COS Guardia Civil Burgos'),
	 (1060,N'COS Guardia Civil Cádiz'),
	 (1061,N'COS Guardia Civil Cuenca'),
	 (1062,N'COS Guardia Civil Guadalajara'),
	 (1063,N'COS Guardia Civil Las Palmas'),
	 (1064,N'COS Guardia Civil León'),
	 (1065,N'COS Guardia Civil Madrid');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1066,N'COS Guardia Civil Navarra'),
	 (1067,N'D.G./S.G.'),
	 (1068,N'Dinamarca, Protección Civil'),
	 (1069,N'Embajada de España en Francia'),
	 (1070,N'Embajada de Marruecos en España'),
	 (1071,N'Francia, Protección Civil'),
	 (1072,N'Grecia, Protección Civil'),
	 (1073,N'Guardia Civil de Tráfico'),
	 (1074,N'Italia, Protección Civil'),
	 (1075,N'Marruecos, Ministerio del Interior');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1076,N'Marruecos, Protección Civil'),
	 (1077,N'Ministerio de Economía y Hacienda'),
	 (1078,N'Policía Municipal de Marbella'),
	 (1079,N'Portugal, Protección Civil'),
	 (1080,N'Presa Itoiz'),
	 (1081,N'RAS-BICHAT'),
	 (1082,N'República Checa, Protección Civil'),
	 (1083,N'Subdelegación del Gobierno en Asturias'),
	 (1084,N'Subdelegación del Gobierno en Badajoz'),
	 (1085,N'C.A. Ceuta');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1086,N'C.A. Melilla'),
	 (1087,N'C.A. Madrid'),
	 (1089,N'Ayuntamiento'),
	 (1090,N'Guardia Civil'),
	 (1091,N'Empresa de servicios'),
	 (1092,N'112 Ceuta'),
	 (1093,N'112 Las Palmas'),
	 (1094,N'Aeropuerto de A Coruña'),
	 (1095,N'Aeropuerto de Albacete'),
	 (1096,N'Aeropuerto de Almería');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1097,N'Aeropuerto de Asturias'),
	 (1098,N'Aeropuerto de Badajoz'),
	 (1099,N'Aeropuerto de Barcelona'),
	 (1100,N'Aeropuerto de Bilbao'),
	 (1101,N'Aeropuerto de Burgos'),
	 (1102,N'Aeropuerto de Córdoba'),
	 (1103,N'Aeropuerto de El Hierro'),
	 (1104,N'Aeropuerto de Fuerteventura'),
	 (1105,N'Aeropuerto de Girona'),
	 (1106,N'Aeropuerto de Gran Canaria');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1107,N'Aeropuerto de Granada'),
	 (1108,N'Aeropuerto de Huesca'),
	 (1109,N'Aeropuerto de Ibiza'),
	 (1110,N'Aeropuerto de Jerez'),
	 (1111,N'Aeropuerto de La Gomera'),
	 (1112,N'Aeropuerto de La Palma'),
	 (1113,N'Aeropuerto de Lanzarote'),
	 (1114,N'Aeropuerto de León'),
	 (1115,N'Aeropuerto de Logroño'),
	 (1116,N'Aeropuerto de Málaga');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1117,N'Aeropuerto de Melilla'),
	 (1118,N'Aeropuerto de Menorca'),
	 (1119,N'Aeropuerto de San Javier'),
	 (1120,N'Aeropuerto de Palma de Mallorca'),
	 (1121,N'Aeropuerto de Reus'),
	 (1122,N'Aeropuerto de Sabadell'),
	 (1123,N'Aeropuerto de Salamanca'),
	 (1124,N'Aeropuerto de San Sebastián'),
	 (1125,N'Aeropuerto de Santander'),
	 (1126,N'Aeropuerto de Santiago');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1127,N'Aeropuerto de Son Bonet'),
	 (1128,N'Aeropuerto de Tenerife Norte (Los Rodeos)'),
	 (1129,N'Aeropuerto de Tenerife Sur (Reina Sofia)'),
	 (1130,N'Aeropuerto de Valencia'),
	 (1131,N'Aeropuerto de Valladolid'),
	 (1132,N'Aeropuerto de Vigo'),
	 (1133,N'Aeropuerto de Vitoria'),
	 (1134,N'Ayuntamiento de Barcelona'),
	 (1135,N'CCAES (Centro de Coordinación de Alertas Sanitarias)'),
	 (1136,N'Central de Incendios Regional');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1137,N'Centro Coordinador de Salvamento'),
	 (1138,N'CECOEL'),
	 (1139,N'Centro de Gestión de Tráfico de Valladolid'),
	 (1140,N'Centro de Gestión de Tráfico de A Coruña'),
	 (1141,N'Centro de Gestión de Tráfico de Valencia'),
	 (1142,N'Centro de Gestión de Tráfico de Málaga '),
	 (1143,N'Centro de Gestión de Tráfico de Sevilla'),
	 (1144,N'Agencia Espacial Europea'),
	 (1145,N'Centro ICE'),
	 (1146,N'Grupo de Predicción y Vigilancia');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1147,N'CIEMAT'),
	 (1148,N'Confederación Hidrográfica del Guadalquivir'),
	 (1149,N'Confederación Hidrográfica del Guadiana'),
	 (1150,N'Confederación Hidrográfica del Júcar'),
	 (1151,N'Confederación Hidrográfica del Miño'),
	 (1152,N'Confederación Hidrográfica del Segura'),
	 (1153,N'Confederación Hidrográfica del Sur de España'),
	 (1154,N'COS Guardia Civil Álava'),
	 (1155,N'COS Guardia Civil Barcelona'),
	 (1156,N'COS Guardia Civil Cantabria');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1157,N'COS Guardia Civil Castellón'),
	 (1158,N'COS Guardia Civil Ceuta'),
	 (1159,N'COS Guardia Civil A Coruña'),
	 (1160,N'COS Guardia Civil Girona'),
	 (1161,N'COS Guardia Civil Granada'),
	 (1162,N'COS Guardia Civil Guipúzcoa'),
	 (1163,N'COS Guardia Civil Huelva'),
	 (1164,N'COS Guardia Civil Huesca'),
	 (1165,N'COS Guardia Civil Illes Balears'),
	 (1166,N'COS Guardia Civil Jaén');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1168,N'COS Guardia Civil Lleida'),
	 (1169,N'COS Guardia Civil Lugo'),
	 (1170,N'COS Guardia Civil Melilla'),
	 (1171,N'COS Guardia Civil Murcia'),
	 (1172,N'COS Guardia Civil Ourense'),
	 (1173,N'COS Guardia Civil Palencia'),
	 (1175,N'COS Guardia Civil Pontevedra'),
	 (1176,N'COS Guardia Civil La Rioja'),
	 (1177,N'COS Guardia Civil Salamanca'),
	 (1178,N'COS Guardia Civil S.C. Tenerife');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1179,N'COS Guardia Civil Segovia'),
	 (1180,N'COS Guardia Civil Soria'),
	 (1181,N'COS Guardia Civil Tarragona'),
	 (1182,N'COS Guardia Civil Toledo'),
	 (1183,N'COS Guardia Civil Valencia'),
	 (1184,N'COS Guardia Civil Valladolid'),
	 (1185,N'COS Guardia Civil Vizcaya'),
	 (1186,N'COS Guardia Civil Zamora'),
	 (1187,N'Cuartel General de la Armada'),
	 (1188,N'Ministerio de Justicia');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1189,N'Ministerio de Industria, Turismo y Comercio'),
	 (1190,N'Ministerio de la Presidencia'),
	 (1191,N'Ministerio de Sanidad, Política Social e Igualdad '),
	 (1192,N'Puesto de Mando AVE'),
	 (1193,N'RCC Canarias'),
	 (1194,N'RCC Madrid'),
	 (1195,N'RCC Palma de Mallorca'),
	 (1196,N'SALEM'),
	 (1197,N'SUMMA 112'),
	 (1198,N'Unión Fenosa');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1199,N'Base Aérea Militar'),
	 (1200,N'CEDEX'),
	 (1201,N'Centro de Control Aéreo'),
	 (1202,N'Centro de Buceo de la Armada'),
	 (1203,N'Centro de Gestión de Red de AENA'),
	 (1204,N'Puesto de Mando Avanzado'),
	 (1205,N'Comisaría'),
	 (1206,N'Consulado'),
	 (1207,N'Dirección General de la Marina Mercante'),
	 (1208,N'Dirección General del Agua');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1209,N'Dirección Insular de la AGE'),
	 (1210,N'Dirección Regional de Navegación Aérea'),
	 (1211,N'ENRESA'),
	 (1212,N'SEPRONA'),
	 (1213,N'Organización Nacional de Trasplantes'),
	 (1214,N'Policía Municipal'),
	 (1215,N'Bomberos'),
	 (1216,N'SAMUR'),
	 (1217,N'NOF, Centro Operativo de Navegación Aérea'),
	 (1218,N'CGA, Aeropuerto de Barajas');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1219,N'República Dominicana'),
	 (1220,N'OTAN Bruselas'),
	 (1221,N'Rumania, Protección Civil'),
	 (1222,N'Reino Unido, Protección Civil'),
	 (1223,N'Suecia, Protección Civil'),
	 (1224,N'Chipre, Protección Civil'),
	 (1225,N'Malta, Protección Civil'),
	 (1226,N'Luxemburgo, Protección Civil'),
	 (1227,N'Central Nuclear de Almaraz'),
	 (1228,N'Central Nuclear de Cofrentes');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1229,N'Central Nuclear de Ascó'),
	 (1230,N'Central Nuclear de Vandellós'),
	 (1231,N'Central Nuclear de Trillo'),
	 (1232,N'Central Nuclear de Santa María de Garoña'),
	 (1233,N'Hungria, Protección Civil'),
	 (1234,N'Eslovenia, Protección Civil'),
	 (1235,N'Noruega, Protección Civil'),
	 (1236,N'OCHA'),
	 (1237,N'ACNUR'),
	 (1238,N'Unidad Carreteras');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1239,N'Capitania Marítima'),
	 (1240,N'MAPAMA'),
	 (1241,N'Central de incendios - Castilla La mancha '),
	 (1242,N'Central de incendios - Castilla y León'),
	 (1243,N'Central incendios - Andalucia'),
	 (1245,N'COR Castilla-La Mancha'),
	 (1246,N'MAPA'),
	 (1247,N'CECO'),
	 (1248,N'COR Incendios Extremadura'),
	 (1249,N'EUCPT');
INSERT INTO dbo.ProcedenciaDestino (Id,Descripcion) VALUES
	 (1250,N'Sala Operaciones Guardia Civil'),
	 (1251,N'CENEM'),
	 (1252,N'MITECO'),
	 (1253,N'COR Andalucía');


SET IDENTITY_INSERT dbo.ProcedenciaDestino OFF;
